version: "3.7"

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: haproxy:log

    ports:
    - 8080:8080
    - 80:80
    
    volumes:
    - ./conf/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    - ./conf/rsyslogs-haproxy.conf:/etc/rsyslog.d/rsyslogs-haproxy.conf
    - ./logs:/var/log/haproxy
